### ISSUE TITLE
Cannot find namespace '’SummarizedExperiment"

### ISSUE THREAD

**Issue by billzyj** [gongx030/scDatasets#2]
Hi, when I run your code 

```r
install_github('gongx030/scDatasets')
```
It said
> Warning: namespace ‘SummarizedExperiment’ is not available and has been replaced by .GlobalEnv when processing object ‘blakeley’

Basically, it cannot find package or namespace ‘SummarizedExperiment’
Would you please explain why this happened? Thanks.

**Comment by zihangwen** [comment]
you can try:
```
install.packages("SingleCellExperiment")
library(SingleCellExperiment)
```

**Comment by billzyj** [comment]
Thanks for your reply! I tried to install SingleCellExperiment package from Bioconductor and now it is working.
